### ISSUE TITLE
Import statement not working

### ISSUE THREAD

**Issue by johnheng** [NicolasDeveloper/guid-typescript#3]
`import { Guid } from "guid-typescript";` causes `error TS2307: Cannot find module 'guid-typescript'.`

`import { Guid } from "guid-typescript/dist/guid";` fixes it

**Comment by kishancool11** [comment]
I am facing the same error. Looks like some issue with new folder structure mentioned in package.json of "guid-typescript" folder

**Comment by ndeeH** [comment]
Facing the same error. Your change crashed our build process. 
We are referenced "^1.0.7" and with version "1.0.8" there is no guid.ts deployed. There is only a "dist\guid.js".
We are now referencing "1.0.7" to stay on the previous version till you fix this...

**Comment by vilemj-Viclick** [comment]
Here's a PR: 
https://github.com/NicolasDeveloper/guid-typescript/pull/4

**Comment by snico-dev** [comment]
sorry, its fixed in version 1.0.9. thanks
